# Generated by Django 4.1 on 2023-06-29 20:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('axis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(verbose_name='Description')),
                ('answer_type', models.SmallIntegerField(choices=[(0, 'Descritiva'), (1, 'Objetiva')], default=1, verbose_name='Answer type')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='axis.axle', verbose_name='Axis')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
