# Generated by Django 4.1 on 2023-04-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
    ]
