# Generated by Django 4.1 on 2023-05-26 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examquestion_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Answered At'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Value'),
        ),
    ]
